# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-14 08:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djedayApp', '0004_auto_20170513_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidates',
            name='master',
        ),
    ]
