# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-14 08:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djedayApp', '0005_remove_candidates_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djedayApp.Djeday'),
        ),
    ]
