# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-14 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djedayApp', '0006_candidates_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otveti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otvet', models.CharField(max_length=50)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djedayApp.Candidates')),
                ('vopros', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djedayApp.Voprosi')),
            ],
        ),
    ]
